import Head from "next/head";
import { AiFillGithub, AiFillLinkedin, AiOutlineFolder } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Contact from "./components/contact";
import { IconContext } from "react-icons";
import Card_temp_1 from "./components/card";
import Card_temp_2 from "./components/card2";
import Card_temp_3 from "./components/card3";
import { FaReact } from "react-icons/fa";
import { SiTypescript } from "react-icons/si";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const [toggle, setToggle] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jazz Harris</title>
        <meta name="description" content="Generated bycreate next app" />
        <link rel="shortcut icon" type="image/png" href="BlackLogo.png" />
      </Head>
      <main className=" bg-white pt-7  dark:bg-gray-900 md:px-5 lg:px-10">
        <script src="../path/to/flowbite/dist/flowbite.js"></script>

        <section id="Home"></section>
        <nav class="bg-white px-2 sm:px-4 py-2.5   dark:bg-slate-600 fixed w-full z-20 top-0 left-0 shadow-lg ">
          <div class="container flex flex-wrap relative items-center mx-auto">
            <a href="#Home" class="flex items-center  ">
              <img src="JHNavLogo.png" alt="logo" class="mr-3 h-6 sm:h-9" />
            </a>
            <div></div>
            <div class="flex md:order-2  ">
              <button
                data-collapse-toggle="navbar-sticky"
                type="button"
                class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-sticky"
                aria-expanded="false"
              >
                <span class="sr-only">Open main menu</span>
                <svg
                  class="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </button>
            </div>
            <div
              class=" w-full md:flex md:w-auto md:order-1  absolute right-0"
              id="navbar-sticky"
            >
              <ul class="flex flex-col p-2   mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-md md:font-medium md:border-0 md:bg-white dark:bg-slate-600 md:dark:bg dark:border-gray-700">
                <li>
                  <a
                    href="#about"
                    class="block py-1 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-cyan-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    About
                  </a>
                </li>

                <li>
                  <a
                    href="#Work"
                    class="block py-1 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-cyan-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    Work
                  </a>
                </li>
                <li>
                  <a
                    href="#Contact"
                    class="block py-1 pr-4 pl-3 text-gray-700 rounded  hover:bg-gray-100 md:hover:bg-transparent md:hover:text-cyan-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    Contact
                  </a>
                </li>
                <button
                  type="button"
                  target="_blank"
                  class="py-0.5 px-2  bg-transparent text-sm hover:bg-cyan-400 text-cyan-400 font-semibold hover:text-white  border border-cyan-400 hover:border-transparent rounded-md"
                  onClick={(e) => {
                    e.preventDefault();
                    window.open(
                      "http://localhost:3000/Jazz(Maura)HarrisResume-1.pdf",
                      "_blank"
                    );
                  }}
                >
                  {" "}
                  Resume
                </button>

                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl  dark:text-white md:hover:text-cyan-400 dark:md:hover:text-cyan-400"
                  />
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div class="icon-bar">
          <a
            className=" text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-cyan-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700 "
            href="https://github.com/Jazz-Harris"
            target="_blank"
          >
            <AiFillGithub />
          </a>
          <a
            className=" text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-cyan-400 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700 "
            href="https://www.linkedin.com/in/maurajharris/"
            target="_blank"
          >
            <AiFillLinkedin />
          </a>
        </div>

        <section className="min-h-screen">
          <div className="container mx-auto px-20 pt-40 flex-1 ">
            <h3 className=" md:text-2xl lg:text-4xl lowercase text-left mb-4 ml-10 p1-10 pt-10 text-gray-800 font-medium dark:text-gray-300 ">
              Hi, My name is
            </h3>
            <div className="container mx-auto px-6 pt-10 flex-1 text-center">
              <h1 className="text-3xl md:text-6xl lg:text-9xl uppercase font-black mb-8 ml-20 p1-20 text-cyan-400 ">
                Jazz Harris
              </h1>
              <br></br>
              <h3 className=" text-2xl md:text-4xl lg:text-5xl pl-12 ml-12 uppercase dark:text-white ">
                Software Developer and Philomath
              </h3>
              <p className=" text-base md:text-lg lg:text-2xl mb-8 pl-12 ml-12  pt-10 mt-5 text-gray-800 dark:text-gray-200 ">
                I'm a software engineer with a passion for learning and solving
                problems
              </p>
            </div>
          </div>
          <section id="about"></section>
        </section>

        <section>
          <div>
            <div className=" p-5 rounded-2xl mx-80 shadow-lg dark:shadow-grey   ">
              <div>
                <div className="w-6/12 sm:w-4/12 px-5">
                  <img
                    src="JHPhoto.png"
                    alt="..."
                    className=" shadow-2xl float-left  w-80 mr-20 rounded-full "
                  />
                </div>
              </div>

              <div className=" ">
                <h3 className="   text-2xl md:text-4xl lg:text-5xl uppercase  mb-8 text-black dark:text-white">
                  About Me
                </h3>

                <p
                  style={{ display: "inline" }}
                  className="  md:text-lg lg:text-2xl leading-8  text-black dark:text-white"
                >
                  My passion to continuously learn new things and watch them
                  come to life initiated my interest in coding. Since then I
                  have the pleasure and privilege of working at a digital
                  marketing agency in Ireland, a local business and a
                  multinational enterprise. Currently, I develop, maintain and
                  upgrade code for a diverse array of clients using various
                  languages, products and digital experiences at Canidium as a
                  Senior Software Analyst.
                </p>

                <br></br>
                <br></br>
                <div className="ml-5">
                  <h1 className="  md:text-2xl   ml-80 pl-20 font-semibold dark: text-cyan-400 dark:text-cyan-400">
                    <bold>Recent technologies I've worked with</bold>

                    <div
                      className="mt-10 mb-10 gap-6"
                      style={{
                        display: "flex",
                        alignItems: "left",
                        justifyContent: "left",
                      }}
                    >
                      <img
                        title="JavaScript"
                        src="https://img.icons8.com/color/48/000000/javascript--v1.png"
                      />
                      <img
                        title="React"
                        src="https://img.icons8.com/color/48/000000/react-native.png"
                      />
                      <img
                        title="Python"
                        src="https://img.icons8.com/color/48/000000/python--v1.png"
                      />
                      <img
                        title="SQL"
                        src="https://img.icons8.com/color/48/000000/sql.png"
                      />
                      <img
                        title="Microsoft Azure"
                        src="https://img.icons8.com/color/48/000000/azure-1.png"
                      />
                      <img
                        title="REST API"
                        img
                        src="https://img.icons8.com/color/48/000000/api-settings.png"
                      />
                    </div>
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div id="Work">
          <section>
            <h1 className=" text-center  pt-20 lg:text-7xl  mr-5 mb-35 mt-60 font-semibold dark: text-black dark:text-white">
              <bold>Work I've done</bold>{" "}
            </h1>

            <div className="flex justify-center ease-linear duration-300 items-center m-20">
              <Card_temp_2 toggle={toggle} settoggle={setToggle} />
            </div>
            <div className="flex justify-center ease-linear duration-300 items-center m-20 ">
              <Card_temp_1 toggle={toggle} settoggle={setToggle} />
            </div>
            <div className="flex justify-center ease-linear duration-300 items-center m-20 ">
              <Card_temp_3 toggle={toggle} settoggle={setToggle} />
            </div>
            <h1
              id="Work"
              className=" text-center  lg:text-4xl  mr-5 mb-5 mt-40  font-semibold dark: text-black dark:text-white"
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <bold>Other Projects</bold>{" "}
            </h1>
            <p class="1xl text-grey text-center mb-2">
              <a
                href="#"
                class="inline-flex items-center text-cyan-400 dark:text-white hover:underline"
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                View more projects
                <svg
                  class="ml-2 w-5 h-5"
                  fill="black"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path>
                  <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path>
                </svg>
              </a>
            </p>

            <section
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <div class="parent">
                <div class="p-10 m-5   max-w-xs  bg-white rounded-lg border border-gray-200 shadow-md dark:bg-slate-700 dark:border-gray-700 dark:hover:bg-gray-500 hover:bg-gray-100 dark:border-gray-700">
                  <IconContext.Provider
                    value={{ className: "top-react-icons" }}
                  >
                    <AiOutlineFolder />
                  </IconContext.Provider>
                  <a href="#">
                    <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">
                      Need a help in Claim?
                    </h5>
                  </a>
                  <p class="font-normal text-gray-500 dark:text-white">
                    Go to this step by step guideline process on how to certify
                    for your weekly benefits:
                  </p>
                  <a
                    href="#"
                    class="inline-flex items-center pt-5  text-cyan-400  dark:text-white hover:underline"
                  >
                    View on GitHub
                    <svg
                      class="ml-2 w-5 h-5"
                      fill="black"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path>
                      <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path>
                    </svg>
                  </a>
                  <div className="flex flex-row items-center m-2 ">
                    <FaReact size={20} color="#61DBFB" />
                    <h1 className="pl-1 dark:text-white">React Native</h1>
                  </div>
                  <div className="flex flex-row items-center m-2">
                    <SiTypescript size={20} color="#007acc" />
                    <h1 className="pl-1 dark:text-white">TypeScript</h1>
                  </div>
                </div>
              </div>
              <div class="parent">
                <div class="p-10 m-5  max-w-xs   bg-white rounded-lg border border-gray-200 shadow-md dark:bg-slate-700 dark:border-gray-700 dark:hover:bg-gray-500 hover:bg-gray-100 dark:border-gray-700">
                  <IconContext.Provider
                    value={{ className: "top-react-icons" }}
                  >
                    <AiOutlineFolder />
                  </IconContext.Provider>
                  <a href="#">
                    <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">
                      Need a help in Claim?
                    </h5>
                  </a>
                  <p class="font-normal text-gray-500 dark:text-white">
                    Go to this step by step guideline process on how to certify
                    for your weekly benefits:
                  </p>
                  <a
                    href="#"
                    class="inline-flex items-center pt-5 text-cyan-400  dark:text-white hover:underline"
                  >
                    View on Github
                    <svg
                      class="ml-2 w-5 h-5"
                      fill="black"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path>
                      <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path>
                    </svg>
                  </a>
                  <div className="flex flex-row items-center m-2 first-letter:">
                    <FaReact size={20} color="#61DBFB" />
                    <h1 className="pl-1 dark:text-white">React Native</h1>
                  </div>
                  <div className="flex flex-row items-center m-2">
                    <SiTypescript size={20} color="#007acc" />
                    <h1 className="pl-1 dark:text-white">TypeScript</h1>
                  </div>
                </div>
              </div>
              <div class="parent">
                <div class="p-10 m-5 max-w-xs   bg-white rounded-lg border border-gray-200 shadow-md dark:bg-slate-700 dark:hover:bg-gray-500 hover:bg-gray-100 dark:border-gray-700">
                  <IconContext.Provider
                    value={{ className: "top-react-icons" }}
                  >
                    <AiOutlineFolder />
                  </IconContext.Provider>
                  <a href="#">
                    <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">
                      Need a help in Claim?
                    </h5>
                  </a>
                  <p class="font-normal text-gray-500 dark:text-white">
                    Go to this step by step guideline process on how to certify
                    for your weekly benefits:
                  </p>
                  <a
                    href="#"
                    class="inline-flex items-center pt-5 text-cyan-400  dark:text-white hover:underline"
                  >
                    View on Github
                    <svg
                      class="ml-2 w-5 h-5"
                      fill="black"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path>
                      <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path>
                    </svg>
                  </a>
                  <div className="flex flex-row items-center m-2 first-letter:">
                    <FaReact size={20} color="#61DBFB" />
                    <h1 className="pl-1 dark:text-white">React Native</h1>
                  </div>
                  <div className="flex flex-row items-center m-2">
                    <SiTypescript size={20} color="#007acc" />
                    <h1 className="pl-1 dark:text-white">TypeScript</h1>
                  </div>
                </div>
              </div>
            </section>
          </section>
        </div>

        <div class="flex min-h-screen items-center text-center  bg-white  dark:bg-gray-900 ">
          <div id="Contact" class="mx-auto w-full max-w-max mt-40">
            <h3 class="my-3 text-7xl mb-8 font-semibold text-black dark:text-white">
              Wanna connect?
            </h3>
            <p class="mt-3 text-3xl  m-4 text-gray-400 dark:text-gray-200">
              I'm always lookng for new opportunities and the prospect to create
              something great!
            </p>
            <p class="mt-3 text-2xl mb-20 text-gray-400  dark:text-gray-200">
              Email me at <span class="text-cyan-400">mharris42@elon.edu</span>{" "}
              or use the form below to send me a message.<br></br>
            </p>
            <div class="shadow-md mx-60  py-10 my-10  rounded-md text-black dark:text-black dark:bg-white dark:shadow-white  flex items-center justify-center">
              <Contact class="shadow-lg dark:shadow-slate-700" />
            </div>
          </div>
        </div>
      </main>

      <footer class=" bg-white mx-10  shadow-2xl md:flex md:items-center md:justify-between md:p-2 dark:bg-gray-800 ">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
          All Rights Reserved.
        </span>
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
          Designed and built by Jazz Harris.
        </span>
      </footer>
    </div>
  );
}
